version: '3'

services:
  db:
    build:
      context: ./database
    ports:
      - ${DB_PORT}:${DB_PORT}
    networks:
      - backend
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - postgres-logs:/var/log/postgresql
  app:
    build:
      context: .
    ports:
      - ${PORT}:${PORT}
    networks:
      - backend
    depends_on:
      - db
    restart: always
    volumes:
      - .:/app
      - /app/node_modules:/app/node_modules:ro
      - ./src:/app/src
networks:
  backend:
    driver: bridge
volumes:
  postgres-data:
  postgres-logs:
